// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4eJWyQg9sXNzAOUszIe5jRvF8jB5Sfc',
    appId: '1:564404762174:web:c2e1491baa064fcf3a836f',
    messagingSenderId: '564404762174',
    projectId: 'island-chat-27d4a',
    authDomain: 'island-chat-27d4a.firebaseapp.com',
    storageBucket: 'island-chat-27d4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BtbD-bCwZcsI9ouZ08sLsFTliGz-Kvc',
    appId: '1:564404762174:android:16a0b5cf52b84bc03a836f',
    messagingSenderId: '564404762174',
    projectId: 'island-chat-27d4a',
    storageBucket: 'island-chat-27d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPYyEDxSXPVFvvz9CKU30ud-CDDyDRZTc',
    appId: '1:564404762174:ios:8fc2ed532015a8f03a836f',
    messagingSenderId: '564404762174',
    projectId: 'island-chat-27d4a',
    storageBucket: 'island-chat-27d4a.appspot.com',
    iosBundleId: 'com.example.islandChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPYyEDxSXPVFvvz9CKU30ud-CDDyDRZTc',
    appId: '1:564404762174:ios:d262e1aa4bc5a3493a836f',
    messagingSenderId: '564404762174',
    projectId: 'island-chat-27d4a',
    storageBucket: 'island-chat-27d4a.appspot.com',
    iosBundleId: 'com.example.islandChat.RunnerTests',
  );
}
